name: mathscool
description: Une application Ã©ducative pour les enfants

version: 2.2.7+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.3.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  foundation: ^0.0.5
  cloud_firestore: ^4.17.5
  lottie: ^2.7.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.5
  path: ^1.8.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  firebase_messaging: ^14.7.0
  permission_handler: ^12.0.0+1
  in_app_purchase: ^3.1.13
  firebase_remote_config: ^4.3.0
  package_info_plus: ^9.0.0
  http: ^1.1.0
  connectivity_plus: ^6.1.1
  audioplayers: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/avatars/
    - assets/images/math_pattern.png
    - assets/sounds/
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700